// lib/models/crop_data.dart
class CropRange {
  final double organicMatterMin;
  final double organicMatterMax;
  final double phosphorusMin;
  final double phosphorusMax;
  final double yieldMin;
  final double yieldMax;

  CropRange({
    required this.organicMatterMin,
    required this.organicMatterMax,
    required this.phosphorusMin,
    required this.phosphorusMax,
    required this.yieldMin,
    required this.yieldMax,
  });
}

// District → Crop → CropRange mapping
final Map<String, Map<String, CropRange>> cropData = {
'Attock': {
'Maize O.P.V': CropRange(
organicMatterMin: 0.28,
organicMatterMax: 0.8,
phosphorusMin: 1.8,
phosphorusMax: 7.0,
yieldMin: 20,
yieldMax: 50,
),
'Tomato': CropRange(
organicMatterMin: 0.5,
organicMatterMax: 1.1,
phosphorusMin: 3.0,
phosphorusMax: 9.0,
yieldMin: 88,
yieldMax: 612,
),
'Wheat': CropRange(
organicMatterMin: 0.37,
organicMatterMax: 0.9,
phosphorusMin: 2.0,
phosphorusMax: 10.2,
yieldMin: 20,
yieldMax: 50,
),
},

'Bahawal Nagar': {
'BT Cotton': CropRange(
organicMatterMin: 0.21,
organicMatterMax: 0.76,
phosphorusMin: 3.8,
phosphorusMax: 12.7,
yieldMin: 7,
yieldMax: 45,
),
'Carrot': CropRange(
organicMatterMin: 0.37,
organicMatterMax: 0.73,
phosphorusMin: 3.5,
phosphorusMax: 10.5,
yieldMin: 128,
yieldMax: 404,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.36,
organicMatterMax: 0.88,
phosphorusMin: 4.8,
phosphorusMax: 14.7,
yieldMin: 3,
yieldMax: 39,
),
'Wheat': CropRange(
organicMatterMin: 0.34,
organicMatterMax: 0.86,
phosphorusMin: 1.7,
phosphorusMax: 14.2,
yieldMin: 20,
yieldMax: 50,
),
},

'Bahawalpur': {
'BT Cotton': CropRange(
organicMatterMin: 0.58,
organicMatterMax: 0.81,
phosphorusMin: 6.0,
phosphorusMax: 9.0,
yieldMin: 8,
yieldMax: 58,
),
'Cabbage': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 0.76,
phosphorusMin: 5.0,
phosphorusMax: 8.4,
yieldMin: 108,
yieldMax: 312,
),
'Carrot': CropRange(
organicMatterMin: 0.3,
organicMatterMax: 0.9,
phosphorusMin: 5.0,
phosphorusMax: 11.0,
yieldMin: 135,
yieldMax: 530,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.36,
organicMatterMax: 0.94,
phosphorusMin: 3.1,
phosphorusMax: 9.6,
yieldMin: 4,
yieldMax: 44,
),
'Sunflower': CropRange(
organicMatterMin: 0.57,
organicMatterMax: 0.86,
phosphorusMin: 6.7,
phosphorusMax: 8.2,
yieldMin: 6,
yieldMax: 29,
),
'Wheat': CropRange(
organicMatterMin: 0.22,
organicMatterMax: 0.89,
phosphorusMin: 3.7,
phosphorusMax: 14.2,
yieldMin: 20,
yieldMax: 55,
),
},

'Bhakkar': {
'Wheat': CropRange(
organicMatterMin: 0.31,
organicMatterMax: 0.83,
phosphorusMin: 2.34,
phosphorusMax: 14.9,
yieldMin: 20,
yieldMax: 47,
),
},

'Chakwal': {
'Wheat': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 0.86,
phosphorusMin: 2.8,
phosphorusMax: 6.0,
yieldMin: 20,
yieldMax: 39,
),
},

'D.G.Khan': {
'BT Cotton': CropRange(
organicMatterMin: 0.44,
organicMatterMax: 0.92,
phosphorusMin: 4.0,
phosphorusMax: 8.8,
yieldMin: 8,
yieldMax: 47,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 0.83,
phosphorusMin: 3.0,
phosphorusMax: 13.0,
yieldMin: 6,
yieldMax: 36,
),
'Wheat': CropRange(
organicMatterMin: 0.38,
organicMatterMax: 1.43,
phosphorusMin: 3.0,
phosphorusMax: 9.0,
yieldMin: 20,
yieldMax: 55,
),
},

'Faisalabad': {
'Basmati rice': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 1.15,
phosphorusMin: 4.0,
phosphorusMax: 18.0,
yieldMin: 20,
yieldMax: 60,
),
'BT Cotton': CropRange(
organicMatterMin: 0.57,
organicMatterMax: 0.93,
phosphorusMin: 2.17,
phosphorusMax: 18.2,
yieldMin: 5,
yieldMax: 60,
),
'Carrot': CropRange(
organicMatterMin: 0.5,
organicMatterMax: 0.92,
phosphorusMin: 3.0,
phosphorusMax: 11.4,
yieldMin: 140,
yieldMax: 471,
),
'Maize O.P.V': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 1.19,
phosphorusMin: 3.0,
phosphorusMax: 15.0,
yieldMin: 20,
yieldMax: 59,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.47,
organicMatterMax: 1.5,
phosphorusMin: 2.1,
phosphorusMax: 15.8,
yieldMin: 6,
yieldMax: 43,
),
'Potato': CropRange(
organicMatterMin: 0.4,
organicMatterMax: 0.94,
phosphorusMin: 5.0,
phosphorusMax: 10.5,
yieldMin: 84,
yieldMax: 426,
),
'Sugarcane': CropRange(
organicMatterMin: 0.52,
organicMatterMax: 1.45,
phosphorusMin: 2.5,
phosphorusMax: 18.3,
yieldMin: 258,
yieldMax: 1004,
),
'Tomato': CropRange(
organicMatterMin: 0.44,
organicMatterMax: 0.84,
phosphorusMin: 5.4,
phosphorusMax: 9.4,
yieldMin: 89,
yieldMax: 329,
),
'Wheat': CropRange(
organicMatterMin: 0.32,
organicMatterMax: 1.24,
phosphorusMin: 1.4,
phosphorusMax: 17.1,
yieldMin: 20,
yieldMax: 60,
),
},

'Gujranwala': {
'Basmati Rice': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 1.05,
phosphorusMin: 4.0,
phosphorusMax: 11.2,
yieldMin: 20,
yieldMax: 62,
),
'Potato': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 0.93,
phosphorusMin: 4.8,
phosphorusMax: 13.6,
yieldMin: 157,
yieldMax: 453,
),
'Wheat': CropRange(
organicMatterMin: 0.42,
organicMatterMax: 1.24,
phosphorusMin: 2.6,
phosphorusMax: 14.5,
yieldMin: 20,
yieldMax: 61,
),
},

'Gujrat': {
'Basmati Rice': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 1.07,
phosphorusMin: 3.5,
phosphorusMax: 17.0,
yieldMin: 20,
yieldMax: 67,
),
'Wheat': CropRange(
organicMatterMin: 0.23,
organicMatterMax: 1.05,
phosphorusMin: 2.6,
phosphorusMax: 17.3,
yieldMin: 20,
yieldMax: 59,
),
},

'Hafizabad': {
'Basmati Rice': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 1.01,
phosphorusMin: 4.4,
phosphorusMax: 16.0,
yieldMin: 20,
yieldMax: 59,
),
'Wheat': CropRange(
organicMatterMin: 0.21,
organicMatterMax: 0.9,
phosphorusMin: 1.2,
phosphorusMax: 16.6,
yieldMin: 20,
yieldMax: 48,
),
},

'Jhang': {
'Basmati': CropRange(
organicMatterMin: 0.26,
organicMatterMax: 0.93,
phosphorusMin: 2.45,
phosphorusMax: 12.6,
yieldMin: 20,
yieldMax: 59,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.31,
organicMatterMax: 0.98,
phosphorusMin: 2.8,
phosphorusMax: 19.8,
yieldMin: 6,
yieldMax: 24,
),
'Potato': CropRange(
organicMatterMin: 0.3,
organicMatterMax: 0.8,
phosphorusMin: 5.0,
phosphorusMax: 10.0,
yieldMin: 88,
yieldMax: 456,
),
'Wheat': CropRange(
organicMatterMin: 0.1,
organicMatterMax: 0.88,
phosphorusMin: 2.5,
phosphorusMax: 11.8,
yieldMin: 20,
yieldMax: 43,
),
},

'Jhelum': {
'Wheat': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 0.9,
phosphorusMin: 2.0,
phosphorusMax: 7.8,
yieldMin: 20,
yieldMax: 52,
),
},

'Kasur': {
'Basmati': CropRange(
organicMatterMin: 0.4,
organicMatterMax: 1.04,
phosphorusMin: 4.2,
phosphorusMax: 16.8,
yieldMin: 20,
yieldMax: 62,
),
'Potato': CropRange(
organicMatterMin: 0.4,
organicMatterMax: 0.94,
phosphorusMin: 5.0,
phosphorusMax: 15.8,
yieldMin: 116,
yieldMax: 481,
),
'Sunflower': CropRange(
organicMatterMin: 0.4,
organicMatterMax: 0.86,
phosphorusMin: 3.0,
phosphorusMax: 7.6,
yieldMin: 9,
yieldMax: 39,
),
'Wheat': CropRange(
organicMatterMin: 0.25,
organicMatterMax: 0.98,
phosphorusMin: 1.2,
phosphorusMax: 11.1,
yieldMin: 20,
yieldMax: 55,
),
},

'Khaniwal': {
'BT Cotton': CropRange(
organicMatterMin: 0.38,
organicMatterMax: 0.93,
phosphorusMin: 3.0,
phosphorusMax: 10.6,
yieldMin: 8,
yieldMax: 53,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.34,
organicMatterMax: 0.85,
phosphorusMin: 2.5,
phosphorusMax: 9.0,
yieldMin: 7,
yieldMax: 35,
),
'Wheat': CropRange(
organicMatterMin: 0.36,
organicMatterMax: 0.95,
phosphorusMin: 3.0,
phosphorusMax: 7.0,
yieldMin: 20,
yieldMax: 49,
),
},

'Khushab': {
'Wheat': CropRange(
organicMatterMin: 0.78,
organicMatterMax: 1.04,
phosphorusMin: 4.3,
phosphorusMax: 9.8,
yieldMin: 20,
yieldMax: 41,
),
},

'Lahore': {
'Basmati Rice': CropRange(
organicMatterMin: 0.28,
organicMatterMax: 0.98,
phosphorusMin: 3.0,
phosphorusMax: 12.3,
yieldMin: 20,
yieldMax: 56,
),
'Wheat': CropRange(
organicMatterMin: 0.48,
organicMatterMax: 1.07,
phosphorusMin: 1.3,
phosphorusMax: 18.0,
yieldMin: 20,
yieldMax: 50,
),
},
'Laayah': { // Layyah
'BT Cotton': CropRange(
organicMatterMin: 0.34,
organicMatterMax: 0.98,
phosphorusMin: 4.7,
phosphorusMax: 10.0,
yieldMin: 7,
yieldMax: 60,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.38,
organicMatterMax: 0.87,
phosphorusMin: 3.0,
phosphorusMax: 10.0,
yieldMin: 7,
yieldMax: 46,
),
'Wheat': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 0.86,
phosphorusMin: 2.0,
phosphorusMax: 9.0,
yieldMin: 20,
yieldMax: 51,
),
},

'M.B.Din': {
'Basmati': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 0.97,
phosphorusMin: 4.0,
phosphorusMax: 10.0,
yieldMin: 20,
yieldMax: 61,
),
'Sugarcane': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 0.76,
phosphorusMin: 4.0,
phosphorusMax: 8.5,
yieldMin: 352,
yieldMax: 1001,
),
'Wheat': CropRange(
organicMatterMin: 0.41,
organicMatterMax: 1.4,
phosphorusMin: 0.5,
phosphorusMax: 8.6,
yieldMin: 20,
yieldMax: 70,
),
},

'Mianwali': {
'Non BT Cotton': CropRange(
organicMatterMin: 0.3,
organicMatterMax: 1.1,
phosphorusMin: 2.5,
phosphorusMax: 11.5,
yieldMin: 5,
yieldMax: 30,
),
'Wheat': CropRange(
organicMatterMin: 0.31,
organicMatterMax: 1.29,
phosphorusMin: 2.05,
phosphorusMax: 13.5,
yieldMin: 20,
yieldMax: 48,
),
},

'Multan': {
'BT Cotton': CropRange(
organicMatterMin: 0.5,
organicMatterMax: 0.95,
phosphorusMin: 5.0,
phosphorusMax: 8.5,
yieldMin: 11,
yieldMax: 59,
),
'Non BT Cotton': CropRange(
organicMatterMin: 0.34,
organicMatterMax: 1.1,
phosphorusMin: 3.0,
phosphorusMax: 10.0,
yieldMin: 6,
yieldMax: 51,
),
'Sunflower': CropRange(
organicMatterMin: 0.34,
organicMatterMax: 0.94,
phosphorusMin: 4.4,
phosphorusMax: 10.4,
yieldMin: 8,
yieldMax: 32,
),
'Tomato': CropRange(
organicMatterMin: 0.36,
organicMatterMax: 0.74,
phosphorusMin: 4.6,
phosphorusMax: 8.4,
yieldMin: 74,
yieldMax: 331,
),
'Wheat': CropRange(
organicMatterMin: 0.4,
organicMatterMax: 1.1,
phosphorusMin: 2.0,
phosphorusMax: 18.0,
yieldMin: 20,
yieldMax: 60,
),
},

'Muzaffar Garh': {
'Non BT Cotton': CropRange(
organicMatterMin: 0.24,
organicMatterMax: 0.87,
phosphorusMin: 2.0,
phosphorusMax: 10.0,
yieldMin: 3,
yieldMax: 29,
),
'Wheat': CropRange(
organicMatterMin: 0.29,
organicMatterMax: 0.99,
phosphorusMin: 2.0,
phosphorusMax: 12.0,
yieldMin: 20,
yieldMax: 66,
),
},

'Narowal': {
'Basmati Rice': CropRange(
organicMatterMin: 0.3,
organicMatterMax: 1.05,
phosphorusMin: 4.0,
phosphorusMax: 19.6,
yieldMin: 20,
yieldMax: 65,
),
'Wheat': CropRange(
organicMatterMin: 0.3,
organicMatterMax: 1.1,
phosphorusMin: 0.4,
phosphorusMax: 11.0,
yieldMin: 20,
yieldMax: 54,
),
},

'Okara': {
'Maiz Hybrid': CropRange(
organicMatterMin: 0.45,
organicMatterMax: 1.0,
phosphorusMin: 4.0,
phosphorusMax: 10.8,
yieldMin: 20,
yieldMax: 69,
),
'Wheat': CropRange(
organicMatterMin: 0.64,
organicMatterMax: 0.99,
phosphorusMin: 3.5,
phosphorusMax: 14.0,
yieldMin: 20,
yieldMax: 50,
),
},

'Pak Pattan': {
'Maiz Hybrid': CropRange(
organicMatterMin: 0.35,
organicMatterMax: 0.97,
phosphorusMin: 3.0,
phosphorusMax: 9.2,
yieldMin: 20,
yieldMax: 67,
),
'Wheat': CropRange(
organicMatterMin: 0.32,
organicMatterMax: 0.98,
phosphorusMin: 4.0,
phosphorusMax: 10.0,
yieldMin: 20,
yieldMax: 49,
),
},
  'R.Y.Khan': {
    'BT Cotton': CropRange(
      organicMatterMin: 0.54,
      organicMatterMax: 0.93,
      phosphorusMin: 4.8,
      phosphorusMax: 8.9,
      yieldMin: 8,
      yieldMax: 59,
    ),
    'Non BT Cotton': CropRange(
      organicMatterMin: 0.23,
      organicMatterMax: 0.98,
      phosphorusMin: 5.0,
      phosphorusMax: 10.5,
      yieldMin: 3,
      yieldMax: 36,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.41,
      organicMatterMax: 0.86,
      phosphorusMin: 4.5,
      phosphorusMax: 17.0,
      yieldMin: 20,
      yieldMax: 45,
    ),
  },

  'Rajan Pur': {
    'Non BT Cotton': CropRange(
      organicMatterMin: 0.41,
      organicMatterMax: 0.74,
      phosphorusMin: 3.0,
      phosphorusMax: 6.0,
      yieldMin: 4,
      yieldMax: 27,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.39,
      organicMatterMax: 0.81,
      phosphorusMin: 3.0,
      phosphorusMax: 7.0,
      yieldMin: 20,
      yieldMax: 52,
    ),
  },

  'Rawalpindi': {
    'Cabbage': CropRange(
      organicMatterMin: 0.42,
      organicMatterMax: 0.95,
      phosphorusMin: 5.5,
      phosphorusMax: 9.0,
      yieldMin: 382,
      yieldMax: 1026,
    ),
    'Garlic': CropRange(
      organicMatterMin: 0.4,
      organicMatterMax: 0.92,
      phosphorusMin: 3.0,
      phosphorusMax: 8.4,
      yieldMin: 29,
      yieldMax: 168,
    ),
    'Maize Hybrid': CropRange(
      organicMatterMin: 0.4,
      organicMatterMax: 1.1,
      phosphorusMin: 4.5,
      phosphorusMax: 11.5,
      yieldMin: 20,
      yieldMax: 99,
    ),
    'Maize O.P.V': CropRange(
      organicMatterMin: 0.3,
      organicMatterMax: 1.1,
      phosphorusMin: 3.1,
      phosphorusMax: 11.0,
      yieldMin: 20,
      yieldMax: 53,
    ),
    'Tomato': CropRange(
      organicMatterMin: 0.5,
      organicMatterMax: 1.15,
      phosphorusMin: 4.0,
      phosphorusMax: 11.0,
      yieldMin: 88,
      yieldMax: 666,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.25,
      organicMatterMax: 1.1,
      phosphorusMin: 1.8,
      phosphorusMax: 9.8,
      yieldMin: 20,
      yieldMax: 49,
    ),
  },

  'Sahiwal': {
    'BT Cotton': CropRange(
      organicMatterMin: 0.47,
      organicMatterMax: 0.98,
      phosphorusMin: 5.5,
      phosphorusMax: 9.5,
      yieldMin: 10,
      yieldMax: 63,
    ),
    'Maiz Hybrid': CropRange(
      organicMatterMin: 0.4,
      organicMatterMax: 1.08,
      phosphorusMin: 3.0,
      phosphorusMax: 11.2,
      yieldMin: 20,
      yieldMax: 99,
    ),
    'Non BT Cotton': CropRange(
      organicMatterMin: 0.4,
      organicMatterMax: 0.8,
      phosphorusMin: 4.0,
      phosphorusMax: 9.0,
      yieldMin: 4,
      yieldMax: 27,
    ),
    'Potato': CropRange(
      organicMatterMin: 0.45,
      organicMatterMax: 0.91,
      phosphorusMin: 4.0,
      phosphorusMax: 12.8,
      yieldMin: 85,
      yieldMax: 483,
    ),
    'Sugarcane': CropRange(
      organicMatterMin: 0.61,
      organicMatterMax: 0.97,
      phosphorusMin: 5.0,
      phosphorusMax: 6.0,
      yieldMin: 185,
      yieldMax: 1032,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.49,
      organicMatterMax: 1.1,
      phosphorusMin: 3.0,
      phosphorusMax: 13.0,
      yieldMin: 20,
      yieldMax: 56,
    ),
  },

  'Sargodha': {
    'Basmati': CropRange(
      organicMatterMin: 0.41,
      organicMatterMax: 1.11,
      phosphorusMin: 3.6,
      phosphorusMax: 17.2,
      yieldMin: 20,
      yieldMax: 59,
    ),
    'Sugarcane': CropRange(
      organicMatterMin: 0.72,
      organicMatterMax: 1.24,
      phosphorusMin: 6.4,
      phosphorusMax: 14.8,
      yieldMin: 304,
      yieldMax: 1218,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.45,
      organicMatterMax: 1.29,
      phosphorusMin: 2.2,
      phosphorusMax: 17.1,
      yieldMin: 20,
      yieldMax: 50,
    ),
  },

  'Sheikhupura': {
    'Basmati': CropRange(
      organicMatterMin: 0.3,
      organicMatterMax: 1.04,
      phosphorusMin: 2.2,
      phosphorusMax: 16.8,
      yieldMin: 20,
      yieldMax: 63,
    ),
    'Sugarcane': CropRange(
      organicMatterMin: 0.55,
      organicMatterMax: 0.97,
      phosphorusMin: 4.9,
      phosphorusMax: 10.2,
      yieldMin: 243,
      yieldMax: 1379,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.21,
      organicMatterMax: 1.45,
      phosphorusMin: 1.4,
      phosphorusMax: 21.9,
      yieldMin: 20,
      yieldMax: 52,
    ),
  },

  'Sialkot': {
    'Basmati': CropRange(
      organicMatterMin: 0.27,
      organicMatterMax: 0.99,
      phosphorusMin: 2.5,
      phosphorusMax: 18.8,
      yieldMin: 20,
      yieldMax: 62,
    ),
    'Potato': CropRange(
      organicMatterMin: 0.45,
      organicMatterMax: 0.97,
      phosphorusMin: 4.0,
      phosphorusMax: 14.4,
      yieldMin: 85,
      yieldMax: 475,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.48,
      organicMatterMax: 1.1,
      phosphorusMin: 0.5,
      phosphorusMax: 13.3,
      yieldMin: 20,
      yieldMax: 60,
    ),
  },

  'T.T.Singh': {
    'BT Cotton': CropRange(
      organicMatterMin: 0.67,
      organicMatterMax: 0.88,
      phosphorusMin: 2.47,
      phosphorusMax: 12.95,
      yieldMin: 6,
      yieldMax: 40,
    ),
    'Maize O.P.V': CropRange(
      organicMatterMin: 0.23,
      organicMatterMax: 0.89,
      phosphorusMin: 2.6,
      phosphorusMax: 15.8,
      yieldMin: 20,
      yieldMax: 58,
    ),
    'Non BT Cotton': CropRange(
      organicMatterMin: 0.62,
      organicMatterMax: 0.91,
      phosphorusMin: 3.15,
      phosphorusMax: 17.9,
      yieldMin: 6,
      yieldMax: 34,
    ),
    'Sugarcane': CropRange(
      organicMatterMin: 0.36,
      organicMatterMax: 0.88,
      phosphorusMin: 3.8,
      phosphorusMax: 13.2,
      yieldMin: 307,
      yieldMax: 1207,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.47,
      organicMatterMax: 1.29,
      phosphorusMin: 1.4,
      phosphorusMax: 12.8,
      yieldMin: 20,
      yieldMax: 56,
    ),
  },

  'Vehari': {
    'BT Cotton': CropRange(
      organicMatterMin: 0.44,
      organicMatterMax: 0.98,
      phosphorusMin: 4.0,
      phosphorusMax: 9.0,
      yieldMin: 10,
      yieldMax: 60,
    ),
    'Non BT Cotton': CropRange(
      organicMatterMin: 0.48,
      organicMatterMax: 0.97,
      phosphorusMin: 2.0,
      phosphorusMax: 13.0,
      yieldMin: 5,
      yieldMax: 33,
    ),
    'Wheat': CropRange(
      organicMatterMin: 0.31,
      organicMatterMax: 0.99,
      phosphorusMin: 3.0,
      phosphorusMax: 10.0,
      yieldMin: 20,
      yieldMax: 55,
    ),
  },
};


