// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxtn5o9wuZYOtP8xITT3QzkGXkaCciQKE',
    appId: '1:270706748969:web:a8144046268a895ebbf638',
    messagingSenderId: '270706748969',
    projectId: 'rightfertilizepakistan',
    authDomain: 'rightfertilizepakistan.firebaseapp.com',
    storageBucket: 'rightfertilizepakistan.firebasestorage.app',
    measurementId: 'G-6DPVMHNH81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWpYkQhgUD5iAo0iKqfkichDIauIKzAQ',
    appId: '1:270706748969:android:59deb235ac6e503cbbf638',
    messagingSenderId: '270706748969',
    projectId: 'rightfertilizepakistan',
    storageBucket: 'rightfertilizepakistan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Om64eoh-DGb8YYP-2VR3owz2bcowpoM',
    appId: '1:270706748969:ios:3cf8d955d0f455b4bbf638',
    messagingSenderId: '270706748969',
    projectId: 'rightfertilizepakistan',
    storageBucket: 'rightfertilizepakistan.firebasestorage.app',
    iosBundleId: 'com.example.rightFertilizePakistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Om64eoh-DGb8YYP-2VR3owz2bcowpoM',
    appId: '1:270706748969:ios:3cf8d955d0f455b4bbf638',
    messagingSenderId: '270706748969',
    projectId: 'rightfertilizepakistan',
    storageBucket: 'rightfertilizepakistan.firebasestorage.app',
    iosBundleId: 'com.example.rightFertilizePakistan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxtn5o9wuZYOtP8xITT3QzkGXkaCciQKE',
    appId: '1:270706748969:web:1d3470b46b219949bbf638',
    messagingSenderId: '270706748969',
    projectId: 'rightfertilizepakistan',
    authDomain: 'rightfertilizepakistan.firebaseapp.com',
    storageBucket: 'rightfertilizepakistan.firebasestorage.app',
    measurementId: 'G-G5TV5SF6P0',
  );
}
